default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: trackfood_development
  username: root
  password: ""
  host: localhost
  port: 3306

test:
  <<: *default
  adapter: mysql2
  database: trackfood_test
  username: root
  password: ""
  host: localhost
  port: 3306

production:
  <<: *default
  adapter: mysql2
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  url: <%= ENV['DATABASE_URL'] %> # Utilise l'URL définie dans les variables d'environnement
