default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: trackfood_development
  username: root
  password:
  host: localhost

test:
  <<: *default
  database: trackfood_test
  username: root
  password:
  host: localhost

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %> # Utilise l'URL définie dans les variables d'environnement
